http:
  listener:
      host: "0.0.0.0"
      port: "8089"
      connectionTimeout: "120000" # 2 minutes
  requester:
      host: "0.0.0.0"
      port: "8089"

ampq:
  host: "localhost"
  port: "5672"
  user: "AndriiDev"
  password: "qwerty12345"   