http:
  listener:
      host: "0.0.0.0"
      port: "8089"
      connectionTimeout: "120000" # 2 minutes
  requester:
      host: "0.0.0.0"
      port: "8089"
      responseTimeout: "120000" # 2 minutes 

amqp:
  host: "hawk-01.rmq.cloudamqp.com"
  port: "5672"
  virtualHost: "dbyxvuzc"
  user: "![ezA1G1UcR9wIslIHXUNNLQ==]"
  password: "![sh5gWkvgzBsydLz7jxod6IgTi9lRhUTSy2T18V5P999VUvhZSRwsNg==]"   